name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6
        with:
          version: 11.5.3

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        id: pnpm-install
        run: pnpm install --frozen-lockfile

      - name: Check Format
        id: pnpm-format-check
        run: pnpm run format:check

      - name: Lint
        id: pnpm-lint
        run: pnpm run lint

      - name: Test
        id: pnpm-ci-test
        run: pnpm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.version }}"
