name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6
        with:
          version: 11.20.0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install Dependencies
        id: pnpm-install
        run: pnpm install --frozen-lockfile

      - name: Check Format
        id: pnpm-format-check
        run: pnpm run format:check

      - name: Lint
        id: pnpm-lint
        run: pnpm run lint

      - name: Test
        id: pnpm-ci-test
        run: pnpm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Test Local Action
        id: test-action
        uses: ./

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.version }}"
